
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  s3_backup:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: S3 Backup
          command: |
            sudo pip3 install -r requirements.txt 
            python3 main.py

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - s3_backup:
          context: s3_backup
